### ISSUE TITLE
Subtember

### ISSUE THREAD

**Issue by seppfury** [Fansubs-co/guide#1]
Yeni başlayacağımızdan şu an sadece ben ve arkadaşımdan oluşan bir fansubız. Umarım aramıza katılmak ve bize yardım etmek istersiniz.
Discord’tan ( seppuku#9590 ) veya instagram hesabımızdan ( thesubtember ) bize ulaşabilirsiniz. ♥

**Comment by Hime-Dev** [comment]
Merhaba burası reklam yeri değildir.
